import { z } from 'zod';

import type { SettingDefinition } from '../../settings/public.js';

const booleanSettingSchema = z.union([
  z.boolean(),
  z.enum(['true', 'false']).transform((value) => value === 'true'),
]);

export const STORAGE_SETTINGS: SettingDefinition[] = [
  {
    key: 'storage.provider',
    group: 'storage',
    groupLabel: '文件存储',
    groupOrder: 50,
    label: '存储驱动',
    description: '本地磁盘适合单机部署；S3 兼容 AWS S3、MinIO、R2 等服务。',
    kind: 'internal',
    schema: z.enum(['local', 's3']),
    environment: 'STORAGE_PROVIDER',
    defaultValue: 'local',
    control: 'select',
    options: [
      { label: '本地磁盘', value: 'local' },
      { label: 'S3 兼容存储', value: 's3' },
    ],
  },
  {
    key: 'storage.s3-region',
    group: 'storage',
    groupLabel: '文件存储',
    groupOrder: 50,
    label: 'S3 Region',
    description: 'S3 服务区域。',
    kind: 'internal',
    schema: z.string().trim().min(1).max(120),
    environment: 'STORAGE_S3_REGION',
    defaultValue: 'us-east-1',
    control: 'text',
  },
  {
    key: 'storage.s3-endpoint',
    group: 'storage',
    groupLabel: '文件存储',
    groupOrder: 50,
    label: 'S3 Endpoint',
    description: '使用 MinIO、R2 等兼容服务时填写；AWS S3 可留空。',
    kind: 'internal',
    schema: z.url().max(1_000),
    environment: 'STORAGE_S3_ENDPOINT',
    control: 'url',
  },
  {
    key: 'storage.s3-bucket',
    group: 'storage',
    groupLabel: '文件存储',
    groupOrder: 50,
    label: 'S3 Bucket',
    description: '对象存储 Bucket；建议保持私有访问。',
    kind: 'internal',
    schema: z.string().trim().min(1).max(255),
    environment: 'STORAGE_S3_BUCKET',
    control: 'text',
  },
  {
    key: 'storage.s3-access-key',
    group: 'storage',
    groupLabel: '文件存储',
    groupOrder: 50,
    label: 'S3 Access Key',
    description: '使用实例角色时可留空。',
    kind: 'secret',
    schema: z.string().min(1).max(1_000),
    environment: 'STORAGE_S3_ACCESS_KEY',
    control: 'text',
  },
  {
    key: 'storage.s3-secret-key',
    group: 'storage',
    groupLabel: '文件存储',
    groupOrder: 50,
    label: 'S3 Secret Key',
    description: '保存后只显示是否已配置。',
    kind: 'secret',
    schema: z.string().min(1).max(2_000),
    environment: 'STORAGE_S3_SECRET_KEY',
    control: 'text',
  },
  {
    key: 'storage.s3-force-path-style',
    group: 'storage',
    groupLabel: '文件存储',
    groupOrder: 50,
    label: '强制 Path-style',
    description: 'MinIO 等兼容服务通常需要开启。',
    kind: 'internal',
    schema: booleanSettingSchema,
    environment: 'STORAGE_S3_FORCE_PATH_STYLE',
    defaultValue: false,
    control: 'boolean',
  },
];
