import { z } from 'zod';

import type { SettingDefinition } from '../../settings/public.js';

const optionalText = z.string().trim().max(320);

export const MAIL_SETTINGS: SettingDefinition[] = [
  {
    key: 'mail.transport',
    group: 'mail',
    groupLabel: '邮件服务',
    groupOrder: 40,
    label: '投递方式',
    description: '开发环境可使用 Capture；生产发送请选择 SMTP。',
    kind: 'internal',
    schema: z.enum(['capture', 'smtp']),
    environment: 'MAIL_TRANSPORT',
    defaultValue: 'capture',
    control: 'select',
    options: [
      { label: 'Capture（不外发）', value: 'capture' },
      { label: 'SMTP', value: 'smtp' },
    ],
  },
  {
    key: 'mail.smtp-host',
    group: 'mail',
    groupLabel: '邮件服务',
    groupOrder: 40,
    label: 'SMTP 主机',
    description: 'SMTP 服务地址。',
    kind: 'internal',
    schema: optionalText.min(1),
    environment: 'SMTP_HOST',
    control: 'text',
  },
  {
    key: 'mail.smtp-port',
    group: 'mail',
    groupLabel: '邮件服务',
    groupOrder: 40,
    label: 'SMTP 端口',
    description: '常用端口为 465 或 587。',
    kind: 'internal',
    schema: z.coerce.number().int().min(1).max(65_535),
    environment: 'SMTP_PORT',
    defaultValue: 587,
    control: 'number',
  },
  {
    key: 'mail.smtp-secure',
    group: 'mail',
    groupLabel: '邮件服务',
    groupOrder: 40,
    label: '直接 TLS',
    description: '465 端口通常启用；587 通常关闭并使用 STARTTLS。',
    kind: 'internal',
    schema: z.union([
      z.boolean(),
      z.enum(['true', 'false']).transform((value) => value === 'true'),
    ]),
    environment: 'SMTP_SECURE',
    defaultValue: false,
    control: 'boolean',
  },
  {
    key: 'mail.smtp-user',
    group: 'mail',
    groupLabel: '邮件服务',
    groupOrder: 40,
    label: 'SMTP 用户名',
    description: 'SMTP 登录账号。',
    kind: 'internal',
    schema: optionalText.min(1),
    environment: 'SMTP_USER',
    control: 'text',
  },
  {
    key: 'mail.smtp-password',
    group: 'mail',
    groupLabel: '邮件服务',
    groupOrder: 40,
    label: 'SMTP 密码',
    description: '加密保存，接口和管理后台永不回显明文。',
    kind: 'secret',
    schema: z.string().min(1).max(500),
    environment: 'SMTP_PASSWORD',
    control: 'text',
  },
  {
    key: 'mail.from-address',
    group: 'mail',
    groupLabel: '邮件服务',
    groupOrder: 40,
    label: '发件地址',
    description: '邮件 From 地址。',
    kind: 'internal',
    schema: z.string().trim().toLowerCase().pipe(z.email().max(320)),
    environment: 'SMTP_FROM_ADDRESS',
    control: 'email',
  },
  {
    key: 'mail.from-name',
    group: 'mail',
    groupLabel: '邮件服务',
    groupOrder: 40,
    label: '发件名称',
    description: '邮件 From 显示名称。',
    kind: 'internal',
    schema: optionalText.min(1).max(120),
    environment: 'SMTP_FROM_NAME',
    defaultValue: 'Application',
    control: 'text',
  },
];
